version: '3'
services:
  app:
    build: build/app
    image: test-app:dev
    container_name: test-app
    tty: true
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/test:cached
    command:
      - /usr/local/bin/app_start.sh
