version: '3'
networks:
  shared-network:
    external: true
services:
  app:
    build: build/app
    image: test-app:dev
    container_name: test-app
    tty: true
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/test:cached
    networks:
      shared-network:
        ipv4_address: 172.25.10.60
    command:
      - /usr/local/bin/app_start.sh
